constraint x_color[1]=2;
constraint x_color[5]=2;
constraint x_color[8]=2;
constraint x_color[12]=2;
constraint x_color[16]=2;


constraint x_color[2]=1;
constraint x_color[7]=1;
constraint x_color[9]=1;
constraint x_color[13]=1;

constraint x_color[3]=4;
constraint x_color[6]=4;
constraint x_color[14]=4;

constraint x_color[4]=3;
constraint x_color[10]=3;
constraint x_color[11]=3;
constraint x_color[15]=3;
